name: Deploy to Firebase and GitHub Pages

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build:prod

    - name: Deploy to Firebase
      if: success()
      uses: w9jds/firebase-action@v13.0.1
      with:
          args: deploy --only hosting
      env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

    - name: Deploy to GitHub Pages
      if: success()
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: dist/angular-firebase-integration
        enable_jekyll: true
