name: Deploy to Firebase and GitHub Pages

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Checkout
      uses: actions/checkout@v2

    - name: Install dependencies
      run:  npm install -g firebase-tools
            npm install

    - name: Build
      run: npm run build:prod
      
    - name: deploy to firebase
      uses: FirebaseExtended/action-hosting-deploy@v0
      with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_ANGULAR_FIRE_DEMO_541C1 }}'
          channelId: live
          projectId: angular-fire-demo-541c1

    - name: Deploy to GitHub Pages
      if: success()
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: dist/angular-firebase-integration
        enable_jekyll: true
